<?php

declare(strict_types=1);

namespace App\Modules\Shipment\Seeders;

use App\Modules\Order\Models\Order;
use App\Modules\Shipment\Models\Shipment;
use App\Modules\Shipment\Models\ShipmentItem;
use Illuminate\Database\Seeder;

/**
 * Seed demo shipments for shipped/delivered orders.
 *
 * @author Sanjiv Kumar Kushwaha
 */
class ShipmentSeeder extends Seeder
{
    public function run(): void
    {
        Order::query()
            ->whereIn('status', [Order::SHIPPED, Order::DELIVERED])
            ->with('items')
            ->chunkById(100, function ($orders): void {
                foreach ($orders as $index => $order) {
                    if (Shipment::where('order_id', $order->id)->exists()) {
                        continue;
                    }

                    $delivered = $order->status === Order::DELIVERED;

                    $shipment = Shipment::create([
                        'order_id' => $order->id,
                        'status' => $delivered ? 'delivered' : 'in_transit',
                        'carrier' => 'BlueDart',
                        'service' => 'Surface',
                        'tracking_number' => 'BD' . str_pad((string) ($order->id * 7919), 10, '0', STR_PAD_LEFT),
                        'tracking_url' => 'https://www.bluedart.com/track',
                        'shipping_address' => $order->shipping_address,
                        'shipped_at' => now()->subDays($delivered ? 7 : 2),
                        'delivered_at' => $delivered ? now()->subDays(2) : null,
                        'notes' => 'Demo shipment generated by seeder.',
                    ]);

                    foreach ($order->items as $item) {
                        ShipmentItem::create([
                            'shipment_id' => $shipment->id,
                            'order_item_id' => $item->id,
                            'product_id' => $item->product_id,
                            'product_variant_id' => $item->product_variant_id,
                            'quantity' => $item->quantity,
                        ]);
                    }
                }
            });
    }
}
