<?php

declare(strict_types=1);

namespace App\Modules\Supplier\Seeders;

use App\Modules\Supplier\Models\Supplier;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

/**
 * Seed demo suppliers.
 *
 * @author Sanjiv Kumar Kushwaha
 */
class SupplierSeeder extends Seeder
{
    public function run(): void
    {
        $suppliers = [
            [
                'supplier_code' => 'SUP-001',
                'company_name' => 'RamDhan Traders Pvt Ltd',
                'contact_person' => 'Ramesh Gupta',
                'email' => 'ramesh@ramdhantraders.test',
                'country_code' => '+91',
                'mobile' => '9876500011',
                'website' => 'https://ramdhantraders.test',
                'gstin' => '07ABCDE1234F1Z5',
                'pan' => 'ABCDE1234F',
                'payment_terms_days' => 30,
                'credit_limit' => 500000,
            ],
            [
                'supplier_code' => 'SUP-002',
                'company_name' => 'Global Electronics Supply',
                'contact_person' => 'Priya Sharma',
                'email' => 'priya@globalelectronics.test',
                'country_code' => '+91',
                'mobile' => '9876500022',
                'website' => 'https://globalelectronics.test',
                'gstin' => '07FGHIJ5678K1Z2',
                'pan' => 'FGHIJ5678K',
                'payment_terms_days' => 15,
                'credit_limit' => 250000,
            ],
        ];

        foreach ($suppliers as $data) {
            Supplier::firstOrCreate(
                ['supplier_code' => $data['supplier_code']],
                $data + [
                    'uuid' => (string) Str::uuid(),
                    'notes' => 'Demo supplier generated by seeder.',
                    'is_active' => true,
                ]
            );
        }
    }
}
