<?php

declare(strict_types=1);

namespace App\Modules\Purchase\Seeders;

use App\Modules\Product\Models\Product;
use App\Modules\Purchase\Models\PurchaseOrder;
use App\Modules\Purchase\Models\PurchaseOrderItem;
use App\Modules\Supplier\Models\Supplier;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

/**
 * Seed demo purchase orders with items.
 *
 * @author Sanjiv Kumar Kushwaha
 */
class PurchaseOrderSeeder extends Seeder
{
    public function run(): void
    {
        $suppliers = Supplier::query()->where('is_active', true)->get();
        $products = Product::query()->where('is_active', true)->take(6)->get();
        $statuses = [PurchaseOrder::APPROVED, PurchaseOrder::RECEIVED, PurchaseOrder::DRAFT];

        if ($suppliers->isEmpty() || $products->isEmpty()) {
            return;
        }

        foreach ($suppliers as $index => $supplier) {
            if (PurchaseOrder::where('supplier_id', $supplier->id)->exists()) {
                continue;
            }

            $status = $statuses[$index % count($statuses)];

            $subtotal = 0;
            $lines = [];

            foreach ($products->forPage($index + 1, 3) ?: $products->take(3) as $product) {
                $qty = 10 + ($product->id % 5) * 10;
                $unitPrice = round((float) $product->cost_price * 0.8, 2);
                $lineSubtotal = $qty * $unitPrice;
                $taxAmount = round($lineSubtotal * 0.18, 2);
                $subtotal += $lineSubtotal;

                $lines[] = [
                    'uuid' => (string) Str::uuid(),
                    'product_id' => $product->id,
                    'sku' => $product->sku,
                    'description' => $product->name,
                    'ordered_quantity' => $qty,
                    'received_quantity' => $status === PurchaseOrder::RECEIVED ? $qty : ($status === PurchaseOrder::APPROVED ? round($qty / 2, 3) : 0),
                    'rejected_quantity' => 0,
                    'unit_price' => $unitPrice,
                    'tax_rate' => 18,
                    'tax_amount' => $taxAmount,
                    'line_subtotal' => $lineSubtotal,
                    'line_total' => $lineSubtotal + $taxAmount,
                ];
            }

            $poNumberStatusMap = [
                PurchaseOrder::APPROVED => ['approved_at' => now()->subDays(2), 'submitted_at' => now()->subDays(3)],
                PurchaseOrder::RECEIVED => ['approved_at' => now()->subDays(9), 'submitted_at' => now()->subDays(10)],
                PurchaseOrder::DRAFT => [],
            ];

            $order = PurchaseOrder::create([
                'supplier_id' => $supplier->id,
                'status' => $status,
                'order_date' => now()->subDays(10 - $index)->toDateString(),
                'expected_date' => now()->addDays(5)->toDateString(),
                'payment_terms_days' => $supplier->payment_terms_days ?? 30,
                'currency_code' => 'INR',
                'subtotal' => $subtotal,
                'tax_amount' => round($subtotal * 0.18, 2),
                'shipping_amount' => 250,
                'grand_total' => round($subtotal * 1.18 + 250, 2),
                'notes' => 'Demo purchase order generated by seeder.',
                ...$poNumberStatusMap[$status],
            ]);

            foreach ($lines as $line) {
                PurchaseOrderItem::create([
                    'purchase_order_id' => $order->id,
                    ...$line,
                ]);
            }
        }
    }
}
